// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2013.03.11 12:35:24 // Generated by ComTest
 *
 */
public class PoistaTaulukostaTest {



  // Generated by ComTest BEGIN
  /** testPoista12 */
  @Test
  public void testPoista12() {    // PoistaTaulukosta: 12
    int a[]= { 1,2,4,3,3,2,4} ; 
    int lkm = 7; 
    assertEquals("From: PoistaTaulukosta line: 15", 5, lkm poista(a, lkm, 3)); 
  } // Generated by ComTest END
}