// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2012.02.01 15:38:01 // Generated by ComTest
 *
 */
public class KolmioTest {



  // Generated by ComTest BEGIN
  /** testKolmionHypotenuusa23 */
  @Test
  public void testKolmionHypotenuusa23() {    // Kolmio: 23
    assertEquals("From: Kolmio line: 25", 3.60, Kolmio.kolmionHypotenuusa(3 ,2), 0.01); 
    assertEquals("From: Kolmio line: 26", 5.00, Kolmio.kolmionHypotenuusa(4 ,3), 0.01); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testKolmionAla44 */
  @Test
  public void testKolmionAla44() {    // Kolmio: 44
    assertEquals("From: Kolmio line: 46", 3.0, Kolmio.kolmionAla(3 ,2), 0.01); 
    assertEquals("From: Kolmio line: 47", 6.0, Kolmio.kolmionAla(4 ,3), 0.01); 
  } // Generated by ComTest END
}