// Generated by ComTest BEGIN
import javax.swing.*;
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2012.02.13 00:18:45 // Generated by ComTest
 *
 */
public class AanestysTest {



  // Generated by ComTest BEGIN
  /** testAanesta156 */
  @Test
  public void testAanesta156() {    // Aanestys: 156
    comtest.GUITester g = new comtest.GUITester(); 
    Aanestys frame = new Aanestys(); 
    g.showWindow(frame); 
    JButton buttonAanesta = g.getComponent(JButton.class); 
    g.click(buttonAanesta); 
    JLabel l = g.getComponent(JLabel.class,g.where.textMatches("Äänes.*")); 
    assertEquals("From: Aanestys line: 164", "Äänestit siis: Tyttö", l.getText()); 
  } // Generated by ComTest END
}