package demo6;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static demo6.Pvm.*;
import demo6.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2013.02.18 01:42:38 // Generated by ComTest
 *
 */
public class PvmTest {



  // Generated by ComTest BEGIN
  /** testKarkausvuosi46 */
  @Test
  public void testKarkausvuosi46() {    // Pvm: 46
    assertEquals("From: Pvm line: 47", 0, karkausvuosi(1900));
    assertEquals("From: Pvm line: 48", 0, karkausvuosi(1900));
    assertEquals("From: Pvm line: 49", 0, karkausvuosi(1901));
    assertEquals("From: Pvm line: 50", 1, karkausvuosi(1996));
    assertEquals("From: Pvm line: 51", 1, karkausvuosi(2000));
    assertEquals("From: Pvm line: 52", 0, karkausvuosi(2001));
    assertEquals("From: Pvm line: 53", 1, karkausvuosi(2004));
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAlusta70 */
  @Test
  public void testAlusta70() {    // Pvm: 70
    Pvm pvmtest = new Pvm(69,2,1988); 
    assertEquals("From: Pvm line: 72", "69.2.1988", pvmtest.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString141 */
  @Test
  public void testToString141() {    // Pvm: 141
    Pvm tammi2011 = new Pvm(1,1,2011); 
    assertEquals("From: Pvm line: 143", "1.1.2011", tammi2011.toString());
    Pvm helmi2011 = new Pvm(1,2,2011); 
    assertEquals("From: Pvm line: 145", "1.2.2011", helmi2011.toString());
    Pvm tanaan = new Pvm(14,2,2011); 
    assertEquals("From: Pvm line: 147", "14.2.2011", tanaan.toString());
    Pvm maalis97 = new Pvm(1,3,1997); 
    assertEquals("From: Pvm line: 149", "1.3.1997", maalis97.toString());
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse188 */
  @Test
  public void testParse188() {    // Pvm: 188
    Pvm pvm = new Pvm(11,3,2003); 
    pvm.parse("12"); assertEquals("From: Pvm line: 190", "12.3.2003", pvm.toString()); 
    pvm.parse("..2001"); assertEquals("From: Pvm line: 191", "12.3.2001", pvm.toString()); 
    pvm.parse("..2009 14:30"); assertEquals("From: Pvm line: 192", "12.3.2009", pvm.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse207 */
  @Test
  public void testParse207() {    // Pvm: 207
    Pvm pvm = new Pvm(11,3,2003); 
    StringBuilder jono = new StringBuilder("12"); 
    pvm.parse(jono); assertEquals("From: Pvm line: 210", "12.3.2003", pvm.toString()); assertEquals("From: Pvm line: 210", "", jono.toString()); 
    jono = new StringBuilder("..2001"); 
    pvm.parse(jono); assertEquals("From: Pvm line: 212", "12.3.2001", pvm.toString()); assertEquals("From: Pvm line: 212", "", jono.toString()); 
    jono = new StringBuilder("..2009 14:30"); 
    pvm.parse(jono); assertEquals("From: Pvm line: 214", "12.3.2009", pvm.toString()); assertEquals("From: Pvm line: 214", "14:30", jono.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetPv227 */
  @Test
  public void testGetPv227() {    // Pvm: 227
    Pvm pv = new Pvm("14.2.2011"); 
    assertEquals("From: Pvm line: 229", 14, pv.getPv()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetKk240 */
  @Test
  public void testGetKk240() {    // Pvm: 240
    Pvm pv = new Pvm("14.2.2011"); 
    assertEquals("From: Pvm line: 242", 2, pv.getKk()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetVv253 */
  @Test
  public void testGetVv253() {    // Pvm: 253
    Pvm pv = new Pvm("14.2.2011"); 
    assertEquals("From: Pvm line: 255", 2011, pv.getVv()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testCompareTo268 */
  @Test
  public void testCompareTo268() {    // Pvm: 268
    Pvm pv1 = new Pvm("14.2.2011"); 
    Pvm pv2 = new Pvm("13.2.2011"); 
    Pvm pv3 = new Pvm("13.3.2011"); 
    Pvm pv4 = new Pvm("13.3.2010"); 
    assertEquals("From: Pvm line: 273", 1, compareTo(pv1, pv2)); 
    assertEquals("From: Pvm line: 274", -1, compareTo(pv2, pv1)); 
    assertEquals("From: Pvm line: 275", -1, compareTo(pv2, pv3)); 
    assertEquals("From: Pvm line: 276", 1, compareTo(pv3, pv4)); 
    assertEquals("From: Pvm line: 277", 0, compareTo(pv4, pv4)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testCompareTo304 */
  @Test
  public void testCompareTo304() {    // Pvm: 304
    Pvm pv1 = new Pvm("1.2.1988"); 
    Pvm pv2 = new Pvm("2.2.1988"); 
    Pvm pv3 = new Pvm("1.3.1988"); 
    Pvm pv4 = new Pvm("1.2.1990"); 
    assertEquals("From: Pvm line: 309", -1, pv1.compareTo(pv2)); 
    assertEquals("From: Pvm line: 310", 1, pv2.compareTo(pv1)); 
    assertEquals("From: Pvm line: 311", -1, pv1.compareTo(pv3)); 
    assertEquals("From: Pvm line: 312", 1, pv4.compareTo(pv3)); 
    assertEquals("From: Pvm line: 313", 0, pv1.compareTo(pv1)); 
  } // Generated by ComTest END
}