package demo6;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import demo6.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2013.02.18 12:40:20 // Generated by ComTest
 *
 */
public class TaulukoitaTest {
}